// Code generated by entc, DO NOT EDIT.

package menuitem

const (
	// Label holds the string label denoting the menuitem type in the database.
	Label = "menu_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldCategoryId holds the string denoting the categoryid field in the database.
	FieldCategoryId = "category_id"
	// Table holds the table name of the menuitem in the database.
	Table = "menu_items"
)

// Columns holds all SQL columns for menuitem fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldImage,
	FieldCategoryId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultImage holds the default value on creation for the "image" field.
	DefaultImage string
	// DefaultCategoryId holds the default value on creation for the "categoryId" field.
	DefaultCategoryId int
)
