@startuml test
left to right direction

object course
object guestMenuItem
object guest
object menuItem
object role
object userGuest
object userRole
object user

user "1" -- "n" guest
user "1" -- "n" role
guest "1" -- "n" menuItem
course "1" -- "n" menuItem

@enduml