// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/kirbby/Menu_Selector/ent/guest"
)

// Guest is the model entity for the Guest schema.
type Guest struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Guest) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case guest.FieldID:
			values[i] = new(sql.NullInt64)
		case guest.FieldName, guest.FieldEmail:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Guest", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Guest fields.
func (gu *Guest) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case guest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			gu.ID = int(value.Int64)
		case guest.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				gu.Name = value.String
			}
		case guest.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				gu.Email = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Guest.
// Note that you need to call Guest.Unwrap() before calling this method if this Guest
// was returned from a transaction, and the transaction was committed or rolled back.
func (gu *Guest) Update() *GuestUpdateOne {
	return (&GuestClient{config: gu.config}).UpdateOne(gu)
}

// Unwrap unwraps the Guest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gu *Guest) Unwrap() *Guest {
	tx, ok := gu.config.driver.(*txDriver)
	if !ok {
		panic("ent: Guest is not a transactional entity")
	}
	gu.config.driver = tx.drv
	return gu
}

// String implements the fmt.Stringer.
func (gu *Guest) String() string {
	var builder strings.Builder
	builder.WriteString("Guest(")
	builder.WriteString(fmt.Sprintf("id=%v", gu.ID))
	builder.WriteString(", name=")
	builder.WriteString(gu.Name)
	builder.WriteString(", email=")
	builder.WriteString(gu.Email)
	builder.WriteByte(')')
	return builder.String()
}

// Guests is a parsable slice of Guest.
type Guests []*Guest

func (gu Guests) config(cfg config) {
	for _i := range gu {
		gu[_i].config = cfg
	}
}
