// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kirbby/Menu_Selector/ent/guest"
)

// GuestCreate is the builder for creating a Guest entity.
type GuestCreate struct {
	config
	mutation *GuestMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (gc *GuestCreate) SetName(s string) *GuestCreate {
	gc.mutation.SetName(s)
	return gc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (gc *GuestCreate) SetNillableName(s *string) *GuestCreate {
	if s != nil {
		gc.SetName(*s)
	}
	return gc
}

// SetEmail sets the "email" field.
func (gc *GuestCreate) SetEmail(s string) *GuestCreate {
	gc.mutation.SetEmail(s)
	return gc
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (gc *GuestCreate) SetNillableEmail(s *string) *GuestCreate {
	if s != nil {
		gc.SetEmail(*s)
	}
	return gc
}

// Mutation returns the GuestMutation object of the builder.
func (gc *GuestCreate) Mutation() *GuestMutation {
	return gc.mutation
}

// Save creates the Guest in the database.
func (gc *GuestCreate) Save(ctx context.Context) (*Guest, error) {
	var (
		err  error
		node *Guest
	)
	gc.defaults()
	if len(gc.hooks) == 0 {
		if err = gc.check(); err != nil {
			return nil, err
		}
		node, err = gc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GuestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = gc.check(); err != nil {
				return nil, err
			}
			gc.mutation = mutation
			if node, err = gc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(gc.hooks) - 1; i >= 0; i-- {
			if gc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GuestCreate) SaveX(ctx context.Context) *Guest {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GuestCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GuestCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gc *GuestCreate) defaults() {
	if _, ok := gc.mutation.Name(); !ok {
		v := guest.DefaultName
		gc.mutation.SetName(v)
	}
	if _, ok := gc.mutation.Email(); !ok {
		v := guest.DefaultEmail
		gc.mutation.SetEmail(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gc *GuestCreate) check() error {
	if _, ok := gc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Guest.name"`)}
	}
	if _, ok := gc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Guest.email"`)}
	}
	return nil
}

func (gc *GuestCreate) sqlSave(ctx context.Context) (*Guest, error) {
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (gc *GuestCreate) createSpec() (*Guest, *sqlgraph.CreateSpec) {
	var (
		_node = &Guest{config: gc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: guest.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: guest.FieldID,
			},
		}
	)
	if value, ok := gc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: guest.FieldName,
		})
		_node.Name = value
	}
	if value, ok := gc.mutation.Email(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: guest.FieldEmail,
		})
		_node.Email = value
	}
	return _node, _spec
}

// GuestCreateBulk is the builder for creating many Guest entities in bulk.
type GuestCreateBulk struct {
	config
	builders []*GuestCreate
}

// Save creates the Guest entities in the database.
func (gcb *GuestCreateBulk) Save(ctx context.Context) ([]*Guest, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Guest, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GuestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GuestCreateBulk) SaveX(ctx context.Context) []*Guest {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GuestCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GuestCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}
