// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kirbby/Menu_Selector/ent/menuitem"
	"github.com/kirbby/Menu_Selector/ent/predicate"
)

// MenuItemUpdate is the builder for updating MenuItem entities.
type MenuItemUpdate struct {
	config
	hooks    []Hook
	mutation *MenuItemMutation
}

// Where appends a list predicates to the MenuItemUpdate builder.
func (miu *MenuItemUpdate) Where(ps ...predicate.MenuItem) *MenuItemUpdate {
	miu.mutation.Where(ps...)
	return miu
}

// SetName sets the "name" field.
func (miu *MenuItemUpdate) SetName(s string) *MenuItemUpdate {
	miu.mutation.SetName(s)
	return miu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (miu *MenuItemUpdate) SetNillableName(s *string) *MenuItemUpdate {
	if s != nil {
		miu.SetName(*s)
	}
	return miu
}

// SetDescription sets the "description" field.
func (miu *MenuItemUpdate) SetDescription(s string) *MenuItemUpdate {
	miu.mutation.SetDescription(s)
	return miu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (miu *MenuItemUpdate) SetNillableDescription(s *string) *MenuItemUpdate {
	if s != nil {
		miu.SetDescription(*s)
	}
	return miu
}

// SetImage sets the "image" field.
func (miu *MenuItemUpdate) SetImage(s string) *MenuItemUpdate {
	miu.mutation.SetImage(s)
	return miu
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (miu *MenuItemUpdate) SetNillableImage(s *string) *MenuItemUpdate {
	if s != nil {
		miu.SetImage(*s)
	}
	return miu
}

// SetCategoryId sets the "categoryId" field.
func (miu *MenuItemUpdate) SetCategoryId(i int) *MenuItemUpdate {
	miu.mutation.ResetCategoryId()
	miu.mutation.SetCategoryId(i)
	return miu
}

// SetNillableCategoryId sets the "categoryId" field if the given value is not nil.
func (miu *MenuItemUpdate) SetNillableCategoryId(i *int) *MenuItemUpdate {
	if i != nil {
		miu.SetCategoryId(*i)
	}
	return miu
}

// AddCategoryId adds i to the "categoryId" field.
func (miu *MenuItemUpdate) AddCategoryId(i int) *MenuItemUpdate {
	miu.mutation.AddCategoryId(i)
	return miu
}

// Mutation returns the MenuItemMutation object of the builder.
func (miu *MenuItemUpdate) Mutation() *MenuItemMutation {
	return miu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (miu *MenuItemUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(miu.hooks) == 0 {
		affected, err = miu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MenuItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			miu.mutation = mutation
			affected, err = miu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(miu.hooks) - 1; i >= 0; i-- {
			if miu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = miu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, miu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (miu *MenuItemUpdate) SaveX(ctx context.Context) int {
	affected, err := miu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (miu *MenuItemUpdate) Exec(ctx context.Context) error {
	_, err := miu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (miu *MenuItemUpdate) ExecX(ctx context.Context) {
	if err := miu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (miu *MenuItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   menuitem.Table,
			Columns: menuitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: menuitem.FieldID,
			},
		},
	}
	if ps := miu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := miu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: menuitem.FieldName,
		})
	}
	if value, ok := miu.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: menuitem.FieldDescription,
		})
	}
	if value, ok := miu.mutation.Image(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: menuitem.FieldImage,
		})
	}
	if value, ok := miu.mutation.CategoryId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: menuitem.FieldCategoryId,
		})
	}
	if value, ok := miu.mutation.AddedCategoryId(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: menuitem.FieldCategoryId,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, miu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{menuitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// MenuItemUpdateOne is the builder for updating a single MenuItem entity.
type MenuItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MenuItemMutation
}

// SetName sets the "name" field.
func (miuo *MenuItemUpdateOne) SetName(s string) *MenuItemUpdateOne {
	miuo.mutation.SetName(s)
	return miuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (miuo *MenuItemUpdateOne) SetNillableName(s *string) *MenuItemUpdateOne {
	if s != nil {
		miuo.SetName(*s)
	}
	return miuo
}

// SetDescription sets the "description" field.
func (miuo *MenuItemUpdateOne) SetDescription(s string) *MenuItemUpdateOne {
	miuo.mutation.SetDescription(s)
	return miuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (miuo *MenuItemUpdateOne) SetNillableDescription(s *string) *MenuItemUpdateOne {
	if s != nil {
		miuo.SetDescription(*s)
	}
	return miuo
}

// SetImage sets the "image" field.
func (miuo *MenuItemUpdateOne) SetImage(s string) *MenuItemUpdateOne {
	miuo.mutation.SetImage(s)
	return miuo
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (miuo *MenuItemUpdateOne) SetNillableImage(s *string) *MenuItemUpdateOne {
	if s != nil {
		miuo.SetImage(*s)
	}
	return miuo
}

// SetCategoryId sets the "categoryId" field.
func (miuo *MenuItemUpdateOne) SetCategoryId(i int) *MenuItemUpdateOne {
	miuo.mutation.ResetCategoryId()
	miuo.mutation.SetCategoryId(i)
	return miuo
}

// SetNillableCategoryId sets the "categoryId" field if the given value is not nil.
func (miuo *MenuItemUpdateOne) SetNillableCategoryId(i *int) *MenuItemUpdateOne {
	if i != nil {
		miuo.SetCategoryId(*i)
	}
	return miuo
}

// AddCategoryId adds i to the "categoryId" field.
func (miuo *MenuItemUpdateOne) AddCategoryId(i int) *MenuItemUpdateOne {
	miuo.mutation.AddCategoryId(i)
	return miuo
}

// Mutation returns the MenuItemMutation object of the builder.
func (miuo *MenuItemUpdateOne) Mutation() *MenuItemMutation {
	return miuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (miuo *MenuItemUpdateOne) Select(field string, fields ...string) *MenuItemUpdateOne {
	miuo.fields = append([]string{field}, fields...)
	return miuo
}

// Save executes the query and returns the updated MenuItem entity.
func (miuo *MenuItemUpdateOne) Save(ctx context.Context) (*MenuItem, error) {
	var (
		err  error
		node *MenuItem
	)
	if len(miuo.hooks) == 0 {
		node, err = miuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MenuItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			miuo.mutation = mutation
			node, err = miuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(miuo.hooks) - 1; i >= 0; i-- {
			if miuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = miuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, miuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (miuo *MenuItemUpdateOne) SaveX(ctx context.Context) *MenuItem {
	node, err := miuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (miuo *MenuItemUpdateOne) Exec(ctx context.Context) error {
	_, err := miuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (miuo *MenuItemUpdateOne) ExecX(ctx context.Context) {
	if err := miuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (miuo *MenuItemUpdateOne) sqlSave(ctx context.Context) (_node *MenuItem, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   menuitem.Table,
			Columns: menuitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: menuitem.FieldID,
			},
		},
	}
	id, ok := miuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MenuItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := miuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, menuitem.FieldID)
		for _, f := range fields {
			if !menuitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != menuitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := miuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := miuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: menuitem.FieldName,
		})
	}
	if value, ok := miuo.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: menuitem.FieldDescription,
		})
	}
	if value, ok := miuo.mutation.Image(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: menuitem.FieldImage,
		})
	}
	if value, ok := miuo.mutation.CategoryId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: menuitem.FieldCategoryId,
		})
	}
	if value, ok := miuo.mutation.AddedCategoryId(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: menuitem.FieldCategoryId,
		})
	}
	_node = &MenuItem{config: miuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, miuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{menuitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
