/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/Guests": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Guests.id"];
          created_at?: parameters["rowFilter.Guests.created_at"];
          name?: parameters["rowFilter.Guests.name"];
          email?: parameters["rowFilter.Guests.email"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Guests"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Guests */
          Guests?: definitions["Guests"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Guests.id"];
          created_at?: parameters["rowFilter.Guests.created_at"];
          name?: parameters["rowFilter.Guests.name"];
          email?: parameters["rowFilter.Guests.email"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Guests.id"];
          created_at?: parameters["rowFilter.Guests.created_at"];
          name?: parameters["rowFilter.Guests.name"];
          email?: parameters["rowFilter.Guests.email"];
        };
        body: {
          /** Guests */
          Guests?: definitions["Guests"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/Users": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Users.id"];
          updated_at?: parameters["rowFilter.Users.updated_at"];
          username?: parameters["rowFilter.Users.username"];
          avatar_url?: parameters["rowFilter.Users.avatar_url"];
          email?: parameters["rowFilter.Users.email"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Users"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Users */
          Users?: definitions["Users"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Users.id"];
          updated_at?: parameters["rowFilter.Users.updated_at"];
          username?: parameters["rowFilter.Users.username"];
          avatar_url?: parameters["rowFilter.Users.avatar_url"];
          email?: parameters["rowFilter.Users.email"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Users.id"];
          updated_at?: parameters["rowFilter.Users.updated_at"];
          username?: parameters["rowFilter.Users.username"];
          avatar_url?: parameters["rowFilter.Users.avatar_url"];
          email?: parameters["rowFilter.Users.email"];
        };
        body: {
          /** Users */
          Users?: definitions["Users"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/Courses": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Courses.id"];
          created_at?: parameters["rowFilter.Courses.created_at"];
          name?: parameters["rowFilter.Courses.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Courses"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Courses */
          Courses?: definitions["Courses"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Courses.id"];
          created_at?: parameters["rowFilter.Courses.created_at"];
          name?: parameters["rowFilter.Courses.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Courses.id"];
          created_at?: parameters["rowFilter.Courses.created_at"];
          name?: parameters["rowFilter.Courses.name"];
        };
        body: {
          /** Courses */
          Courses?: definitions["Courses"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/MenuItems": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.MenuItems.id"];
          created_at?: parameters["rowFilter.MenuItems.created_at"];
          name?: parameters["rowFilter.MenuItems.name"];
          description?: parameters["rowFilter.MenuItems.description"];
          imageUrl?: parameters["rowFilter.MenuItems.imageUrl"];
          courseId?: parameters["rowFilter.MenuItems.courseId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["MenuItems"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** MenuItems */
          MenuItems?: definitions["MenuItems"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.MenuItems.id"];
          created_at?: parameters["rowFilter.MenuItems.created_at"];
          name?: parameters["rowFilter.MenuItems.name"];
          description?: parameters["rowFilter.MenuItems.description"];
          imageUrl?: parameters["rowFilter.MenuItems.imageUrl"];
          courseId?: parameters["rowFilter.MenuItems.courseId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.MenuItems.id"];
          created_at?: parameters["rowFilter.MenuItems.created_at"];
          name?: parameters["rowFilter.MenuItems.name"];
          description?: parameters["rowFilter.MenuItems.description"];
          imageUrl?: parameters["rowFilter.MenuItems.imageUrl"];
          courseId?: parameters["rowFilter.MenuItems.courseId"];
        };
        body: {
          /** MenuItems */
          MenuItems?: definitions["MenuItems"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  Guests: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /** Format: text */
    name: string;
    /** Format: text */
    email?: string;
  };
  Users: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
    /** Format: text */
    username?: string;
    /** Format: text */
    avatar_url?: string;
    /** Format: text */
    email?: string;
  };
  Courses: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    name: string;
  };
  MenuItems: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /** Format: text */
    name: string;
    /** Format: text */
    description?: string;
    /** Format: text */
    imageUrl?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `Courses.id`.<fk table='Courses' column='id'/>
     */
    courseId?: number;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description Guests */
  "body.Guests": definitions["Guests"];
  /** Format: bigint */
  "rowFilter.Guests.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.Guests.created_at": string;
  /** Format: text */
  "rowFilter.Guests.name": string;
  /** Format: text */
  "rowFilter.Guests.email": string;
  /** @description Users */
  "body.Users": definitions["Users"];
  /** Format: uuid */
  "rowFilter.Users.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.Users.updated_at": string;
  /** Format: text */
  "rowFilter.Users.username": string;
  /** Format: text */
  "rowFilter.Users.avatar_url": string;
  /** Format: text */
  "rowFilter.Users.email": string;
  /** @description Courses */
  "body.Courses": definitions["Courses"];
  /** Format: bigint */
  "rowFilter.Courses.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.Courses.created_at": string;
  /** Format: text */
  "rowFilter.Courses.name": string;
  /** @description MenuItems */
  "body.MenuItems": definitions["MenuItems"];
  /** Format: bigint */
  "rowFilter.MenuItems.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.MenuItems.created_at": string;
  /** Format: text */
  "rowFilter.MenuItems.name": string;
  /** Format: text */
  "rowFilter.MenuItems.description": string;
  /** Format: text */
  "rowFilter.MenuItems.imageUrl": string;
  /** Format: bigint */
  "rowFilter.MenuItems.courseId": string;
}

export interface operations {}

export interface external {}
