/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/projects": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects.id"];
          created_at?: parameters["rowFilter.projects.created_at"];
          updated_at?: parameters["rowFilter.projects.updated_at"];
          name?: parameters["rowFilter.projects.name"];
          userId?: parameters["rowFilter.projects.userId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["projects"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** projects */
          projects?: definitions["projects"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects.id"];
          created_at?: parameters["rowFilter.projects.created_at"];
          updated_at?: parameters["rowFilter.projects.updated_at"];
          name?: parameters["rowFilter.projects.name"];
          userId?: parameters["rowFilter.projects.userId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.projects.id"];
          created_at?: parameters["rowFilter.projects.created_at"];
          updated_at?: parameters["rowFilter.projects.updated_at"];
          name?: parameters["rowFilter.projects.name"];
          userId?: parameters["rowFilter.projects.userId"];
        };
        body: {
          /** projects */
          projects?: definitions["projects"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/guestMenuItems": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guestMenuItems.id"];
          menuItemId?: parameters["rowFilter.guestMenuItems.menuItemId"];
          created_at?: parameters["rowFilter.guestMenuItems.created_at"];
          updated_at?: parameters["rowFilter.guestMenuItems.updated_at"];
          guestId?: parameters["rowFilter.guestMenuItems.guestId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["guestMenuItems"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** guestMenuItems */
          guestMenuItems?: definitions["guestMenuItems"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guestMenuItems.id"];
          menuItemId?: parameters["rowFilter.guestMenuItems.menuItemId"];
          created_at?: parameters["rowFilter.guestMenuItems.created_at"];
          updated_at?: parameters["rowFilter.guestMenuItems.updated_at"];
          guestId?: parameters["rowFilter.guestMenuItems.guestId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guestMenuItems.id"];
          menuItemId?: parameters["rowFilter.guestMenuItems.menuItemId"];
          created_at?: parameters["rowFilter.guestMenuItems.created_at"];
          updated_at?: parameters["rowFilter.guestMenuItems.updated_at"];
          guestId?: parameters["rowFilter.guestMenuItems.guestId"];
        };
        body: {
          /** guestMenuItems */
          guestMenuItems?: definitions["guestMenuItems"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/userGuests": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.userGuests.id"];
          created_at?: parameters["rowFilter.userGuests.created_at"];
          updated_at?: parameters["rowFilter.userGuests.updated_at"];
          userId?: parameters["rowFilter.userGuests.userId"];
          guestId?: parameters["rowFilter.userGuests.guestId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["userGuests"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** userGuests */
          userGuests?: definitions["userGuests"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.userGuests.id"];
          created_at?: parameters["rowFilter.userGuests.created_at"];
          updated_at?: parameters["rowFilter.userGuests.updated_at"];
          userId?: parameters["rowFilter.userGuests.userId"];
          guestId?: parameters["rowFilter.userGuests.guestId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.userGuests.id"];
          created_at?: parameters["rowFilter.userGuests.created_at"];
          updated_at?: parameters["rowFilter.userGuests.updated_at"];
          userId?: parameters["rowFilter.userGuests.userId"];
          guestId?: parameters["rowFilter.userGuests.guestId"];
        };
        body: {
          /** userGuests */
          userGuests?: definitions["userGuests"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/guests": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guests.id"];
          created_at?: parameters["rowFilter.guests.created_at"];
          name?: parameters["rowFilter.guests.name"];
          updated_at?: parameters["rowFilter.guests.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["guests"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** guests */
          guests?: definitions["guests"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guests.id"];
          created_at?: parameters["rowFilter.guests.created_at"];
          name?: parameters["rowFilter.guests.name"];
          updated_at?: parameters["rowFilter.guests.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guests.id"];
          created_at?: parameters["rowFilter.guests.created_at"];
          name?: parameters["rowFilter.guests.name"];
          updated_at?: parameters["rowFilter.guests.updated_at"];
        };
        body: {
          /** guests */
          guests?: definitions["guests"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/users": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          updated_at?: parameters["rowFilter.users.updated_at"];
          username?: parameters["rowFilter.users.username"];
          avatar_url?: parameters["rowFilter.users.avatar_url"];
          email?: parameters["rowFilter.users.email"];
          created_at?: parameters["rowFilter.users.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["users"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** users */
          users?: definitions["users"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          updated_at?: parameters["rowFilter.users.updated_at"];
          username?: parameters["rowFilter.users.username"];
          avatar_url?: parameters["rowFilter.users.avatar_url"];
          email?: parameters["rowFilter.users.email"];
          created_at?: parameters["rowFilter.users.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          updated_at?: parameters["rowFilter.users.updated_at"];
          username?: parameters["rowFilter.users.username"];
          avatar_url?: parameters["rowFilter.users.avatar_url"];
          email?: parameters["rowFilter.users.email"];
          created_at?: parameters["rowFilter.users.created_at"];
        };
        body: {
          /** users */
          users?: definitions["users"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/userRoles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.userRoles.id"];
          created_at?: parameters["rowFilter.userRoles.created_at"];
          updated_at?: parameters["rowFilter.userRoles.updated_at"];
          userId?: parameters["rowFilter.userRoles.userId"];
          roleId?: parameters["rowFilter.userRoles.roleId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["userRoles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** userRoles */
          userRoles?: definitions["userRoles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.userRoles.id"];
          created_at?: parameters["rowFilter.userRoles.created_at"];
          updated_at?: parameters["rowFilter.userRoles.updated_at"];
          userId?: parameters["rowFilter.userRoles.userId"];
          roleId?: parameters["rowFilter.userRoles.roleId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.userRoles.id"];
          created_at?: parameters["rowFilter.userRoles.created_at"];
          updated_at?: parameters["rowFilter.userRoles.updated_at"];
          userId?: parameters["rowFilter.userRoles.userId"];
          roleId?: parameters["rowFilter.userRoles.roleId"];
        };
        body: {
          /** userRoles */
          userRoles?: definitions["userRoles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/courses": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.courses.id"];
          created_at?: parameters["rowFilter.courses.created_at"];
          name?: parameters["rowFilter.courses.name"];
          updated_at?: parameters["rowFilter.courses.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["courses"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** courses */
          courses?: definitions["courses"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.courses.id"];
          created_at?: parameters["rowFilter.courses.created_at"];
          name?: parameters["rowFilter.courses.name"];
          updated_at?: parameters["rowFilter.courses.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.courses.id"];
          created_at?: parameters["rowFilter.courses.created_at"];
          name?: parameters["rowFilter.courses.name"];
          updated_at?: parameters["rowFilter.courses.updated_at"];
        };
        body: {
          /** courses */
          courses?: definitions["courses"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/menuItems": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menuItems.id"];
          created_at?: parameters["rowFilter.menuItems.created_at"];
          name?: parameters["rowFilter.menuItems.name"];
          description?: parameters["rowFilter.menuItems.description"];
          imageUrl?: parameters["rowFilter.menuItems.imageUrl"];
          courseId?: parameters["rowFilter.menuItems.courseId"];
          updated_at?: parameters["rowFilter.menuItems.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["menuItems"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** menuItems */
          menuItems?: definitions["menuItems"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menuItems.id"];
          created_at?: parameters["rowFilter.menuItems.created_at"];
          name?: parameters["rowFilter.menuItems.name"];
          description?: parameters["rowFilter.menuItems.description"];
          imageUrl?: parameters["rowFilter.menuItems.imageUrl"];
          courseId?: parameters["rowFilter.menuItems.courseId"];
          updated_at?: parameters["rowFilter.menuItems.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.menuItems.id"];
          created_at?: parameters["rowFilter.menuItems.created_at"];
          name?: parameters["rowFilter.menuItems.name"];
          description?: parameters["rowFilter.menuItems.description"];
          imageUrl?: parameters["rowFilter.menuItems.imageUrl"];
          courseId?: parameters["rowFilter.menuItems.courseId"];
          updated_at?: parameters["rowFilter.menuItems.updated_at"];
        };
        body: {
          /** menuItems */
          menuItems?: definitions["menuItems"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/roles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.roles.id"];
          created_at?: parameters["rowFilter.roles.created_at"];
          updated_at?: parameters["rowFilter.roles.updated_at"];
          name?: parameters["rowFilter.roles.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["roles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** roles */
          roles?: definitions["roles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.roles.id"];
          created_at?: parameters["rowFilter.roles.created_at"];
          updated_at?: parameters["rowFilter.roles.updated_at"];
          name?: parameters["rowFilter.roles.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.roles.id"];
          created_at?: parameters["rowFilter.roles.created_at"];
          updated_at?: parameters["rowFilter.roles.updated_at"];
          name?: parameters["rowFilter.roles.name"];
        };
        body: {
          /** roles */
          roles?: definitions["roles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/userProjects": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.userProjects.id"];
          created_at?: parameters["rowFilter.userProjects.created_at"];
          updated_at?: parameters["rowFilter.userProjects.updated_at"];
          projectId?: parameters["rowFilter.userProjects.projectId"];
          userId?: parameters["rowFilter.userProjects.userId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["userProjects"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** userProjects */
          userProjects?: definitions["userProjects"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.userProjects.id"];
          created_at?: parameters["rowFilter.userProjects.created_at"];
          updated_at?: parameters["rowFilter.userProjects.updated_at"];
          projectId?: parameters["rowFilter.userProjects.projectId"];
          userId?: parameters["rowFilter.userProjects.userId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.userProjects.id"];
          created_at?: parameters["rowFilter.userProjects.created_at"];
          updated_at?: parameters["rowFilter.userProjects.updated_at"];
          projectId?: parameters["rowFilter.userProjects.projectId"];
          userId?: parameters["rowFilter.userProjects.userId"];
        };
        body: {
          /** userProjects */
          userProjects?: definitions["userProjects"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  projects: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
    /** Format: text */
    name?: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    userId: string;
  };
  guestMenuItems: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `menuItems.id`.<fk table='menuItems' column='id'/>
     */
    menuItemId: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `guests.id`.<fk table='guests' column='id'/>
     */
    guestId: number;
  };
  userGuests: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    userId: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `guests.id`.<fk table='guests' column='id'/>
     */
    guestId: number;
  };
  guests: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    name: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
  };
  users: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
    /** Format: text */
    username: string;
    /** Format: text */
    avatar_url?: string;
    /** Format: text */
    email: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
  };
  userRoles: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    userId: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `roles.id`.<fk table='roles' column='id'/>
     */
    roleId: number;
  };
  courses: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    name: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
  };
  menuItems: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    name: string;
    /** Format: text */
    description?: string;
    /** Format: text */
    imageUrl?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `courses.id`.<fk table='courses' column='id'/>
     */
    courseId?: number;
    /** Format: timestamp with time zone */
    updated_at?: string;
  };
  roles: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
    /** Format: text */
    name: string;
  };
  userProjects: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `projects.id`.<fk table='projects' column='id'/>
     */
    projectId: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    userId: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description projects */
  "body.projects": definitions["projects"];
  /** Format: uuid */
  "rowFilter.projects.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.projects.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.projects.updated_at": string;
  /** Format: text */
  "rowFilter.projects.name": string;
  /** Format: uuid */
  "rowFilter.projects.userId": string;
  /** @description guestMenuItems */
  "body.guestMenuItems": definitions["guestMenuItems"];
  /** Format: bigint */
  "rowFilter.guestMenuItems.id": string;
  /** Format: bigint */
  "rowFilter.guestMenuItems.menuItemId": string;
  /** Format: timestamp with time zone */
  "rowFilter.guestMenuItems.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.guestMenuItems.updated_at": string;
  /** Format: bigint */
  "rowFilter.guestMenuItems.guestId": string;
  /** @description userGuests */
  "body.userGuests": definitions["userGuests"];
  /** Format: bigint */
  "rowFilter.userGuests.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.userGuests.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.userGuests.updated_at": string;
  /** Format: uuid */
  "rowFilter.userGuests.userId": string;
  /** Format: bigint */
  "rowFilter.userGuests.guestId": string;
  /** @description guests */
  "body.guests": definitions["guests"];
  /** Format: bigint */
  "rowFilter.guests.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.guests.created_at": string;
  /** Format: text */
  "rowFilter.guests.name": string;
  /** Format: timestamp with time zone */
  "rowFilter.guests.updated_at": string;
  /** @description users */
  "body.users": definitions["users"];
  /** Format: uuid */
  "rowFilter.users.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.users.updated_at": string;
  /** Format: text */
  "rowFilter.users.username": string;
  /** Format: text */
  "rowFilter.users.avatar_url": string;
  /** Format: text */
  "rowFilter.users.email": string;
  /** Format: timestamp with time zone */
  "rowFilter.users.created_at": string;
  /** @description userRoles */
  "body.userRoles": definitions["userRoles"];
  /** Format: bigint */
  "rowFilter.userRoles.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.userRoles.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.userRoles.updated_at": string;
  /** Format: uuid */
  "rowFilter.userRoles.userId": string;
  /** Format: bigint */
  "rowFilter.userRoles.roleId": string;
  /** @description courses */
  "body.courses": definitions["courses"];
  /** Format: bigint */
  "rowFilter.courses.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.courses.created_at": string;
  /** Format: text */
  "rowFilter.courses.name": string;
  /** Format: timestamp with time zone */
  "rowFilter.courses.updated_at": string;
  /** @description menuItems */
  "body.menuItems": definitions["menuItems"];
  /** Format: bigint */
  "rowFilter.menuItems.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.menuItems.created_at": string;
  /** Format: text */
  "rowFilter.menuItems.name": string;
  /** Format: text */
  "rowFilter.menuItems.description": string;
  /** Format: text */
  "rowFilter.menuItems.imageUrl": string;
  /** Format: bigint */
  "rowFilter.menuItems.courseId": string;
  /** Format: timestamp with time zone */
  "rowFilter.menuItems.updated_at": string;
  /** @description roles */
  "body.roles": definitions["roles"];
  /** Format: bigint */
  "rowFilter.roles.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.roles.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.roles.updated_at": string;
  /** Format: text */
  "rowFilter.roles.name": string;
  /** @description userProjects */
  "body.userProjects": definitions["userProjects"];
  /** Format: uuid */
  "rowFilter.userProjects.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.userProjects.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.userProjects.updated_at": string;
  /** Format: uuid */
  "rowFilter.userProjects.projectId": string;
  /** Format: uuid */
  "rowFilter.userProjects.userId": string;
}

export interface operations {}

export interface external {}
