// Code generated by entc, DO NOT EDIT.

package http

import (
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/kirbby/Menu_Selector/ent"
	"go.uber.org/zap"
)

// NewHandler returns a ready to use handler with all generated endpoints mounted.
func NewHandler(c *ent.Client, l *zap.Logger) chi.Router {
	r := chi.NewRouter()
	MountRoutes(c, l, r)
	return r
}

// MountRoutes mounts all generated routes on the given router.
func MountRoutes(c *ent.Client, l *zap.Logger, r chi.Router) {
	NewGuestHandler(c, l).MountRoutes(r)
}

// GuestHandler handles http crud operations on ent.Guest.
type GuestHandler struct {
	client *ent.Client
	log    *zap.Logger
}

func NewGuestHandler(c *ent.Client, l *zap.Logger) *GuestHandler {
	return &GuestHandler{
		client: c,
		log:    l.With(zap.String("handler", "GuestHandler")),
	}
}
func (h *GuestHandler) MountCreateRoute(r chi.Router) *GuestHandler {
	r.Post("/guests", h.Create)
	return h
}
func (h *GuestHandler) MountReadRoute(r chi.Router) *GuestHandler {
	r.Get("/guests/{id}", h.Read)
	return h
}
func (h *GuestHandler) MountUpdateRoute(r chi.Router) *GuestHandler {
	r.Patch("/guests/{id}", h.Update)
	return h
}
func (h *GuestHandler) MountDeleteRoute(r chi.Router) *GuestHandler {
	r.Delete("/guests/{id}", h.Delete)
	return h
}
func (h *GuestHandler) MountListRoute(r chi.Router) *GuestHandler {
	r.Get("/guests", h.List)
	return h
}
func (h *GuestHandler) MountRoutes(r chi.Router) {
	h.MountCreateRoute(r).MountReadRoute(r).MountUpdateRoute(r).MountDeleteRoute(r).MountListRoute(r)
}

func stripEntError(err error) string {
	return strings.TrimPrefix(err.Error(), "ent: ")
}

func zapFields(errs map[string]string) []zap.Field {
	if errs == nil || len(errs) == 0 {
		return nil
	}
	r := make([]zap.Field, 0)
	for k, v := range errs {
		r = append(r, zap.String(k, v))
	}
	return r
}
