// Code generated by entc, DO NOT EDIT.

package http

// Payload of a ent.Guest create request.
type GuestCreateRequest struct {
	Name  *string `json:"name"`
	Email *string `json:"email"`
}

// Payload of a ent.Guest update request.
type GuestUpdateRequest struct {
	Name  *string `json:"name"`
	Email *string `json:"email"`
}
