// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GuestsColumns holds the columns for the "guests" table.
	GuestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
	}
	// GuestsTable holds the schema information for the "guests" table.
	GuestsTable = &schema.Table{
		Name:       "guests",
		Columns:    GuestsColumns,
		PrimaryKey: []*schema.Column{GuestsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GuestsTable,
	}
)

func init() {
}
