// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateGuestRes interface {
	createGuestRes()
}

type CreateMenuItemRes interface {
	createMenuItemRes()
}

type DeleteGuestRes interface {
	deleteGuestRes()
}

type DeleteMenuItemRes interface {
	deleteMenuItemRes()
}

type ListGuestRes interface {
	listGuestRes()
}

type ListMenuItemRes interface {
	listMenuItemRes()
}

type ReadGuestRes interface {
	readGuestRes()
}

type ReadMenuItemRes interface {
	readMenuItemRes()
}

type UpdateGuestRes interface {
	updateGuestRes()
}

type UpdateMenuItemRes interface {
	updateMenuItemRes()
}
