// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"math"
	"math/big"
	"math/bits"
	"net"
	"net/http"
	"net/url"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/json"
	"github.com/ogen-go/ogen/otelogen"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

// No-op definition for keeping imports.
var (
	_ = context.Background()
	_ = fmt.Stringer(nil)
	_ = strings.Builder{}
	_ = errors.Is
	_ = sort.Ints
	_ = http.MethodGet
	_ = io.Copy
	_ = json.Marshal
	_ = bytes.NewReader
	_ = strconv.ParseInt
	_ = time.Time{}
	_ = conv.ToInt32
	_ = uuid.UUID{}
	_ = uri.PathEncoder{}
	_ = url.URL{}
	_ = math.Mod
	_ = bits.LeadingZeros64
	_ = big.Rat{}
	_ = validate.Int{}
	_ = ht.NewRequest
	_ = net.IP{}
	_ = otelogen.Version
	_ = attribute.KeyValue{}
	_ = trace.TraceIDFromHex
	_ = otel.GetTracerProvider
	_ = metric.NewNoopMeterProvider
	_ = regexp.MustCompile
	_ = jx.Null
	_ = sync.Pool{}
	_ = codes.Unset
)

var _ Handler = UnimplementedHandler{}

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

// CreateGuest implements createGuest operation.
//
// Creates a new Guest and persists it to storage.
//
// POST /guests
func (UnimplementedHandler) CreateGuest(ctx context.Context, req CreateGuestReq) (r CreateGuestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMenuItem implements createMenuItem operation.
//
// Creates a new MenuItem and persists it to storage.
//
// POST /menu-items
func (UnimplementedHandler) CreateMenuItem(ctx context.Context, req CreateMenuItemReq) (r CreateMenuItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteGuest implements deleteGuest operation.
//
// Deletes the Guest with the requested ID.
//
// DELETE /guests/{id}
func (UnimplementedHandler) DeleteGuest(ctx context.Context, params DeleteGuestParams) (r DeleteGuestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMenuItem implements deleteMenuItem operation.
//
// Deletes the MenuItem with the requested ID.
//
// DELETE /menu-items/{id}
func (UnimplementedHandler) DeleteMenuItem(ctx context.Context, params DeleteMenuItemParams) (r DeleteMenuItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGuest implements listGuest operation.
//
// List Guests.
//
// GET /guests
func (UnimplementedHandler) ListGuest(ctx context.Context, params ListGuestParams) (r ListGuestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMenuItem implements listMenuItem operation.
//
// List MenuItems.
//
// GET /menu-items
func (UnimplementedHandler) ListMenuItem(ctx context.Context, params ListMenuItemParams) (r ListMenuItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadGuest implements readGuest operation.
//
// Finds the Guest with the requested ID and returns it.
//
// GET /guests/{id}
func (UnimplementedHandler) ReadGuest(ctx context.Context, params ReadGuestParams) (r ReadGuestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadMenuItem implements readMenuItem operation.
//
// Finds the MenuItem with the requested ID and returns it.
//
// GET /menu-items/{id}
func (UnimplementedHandler) ReadMenuItem(ctx context.Context, params ReadMenuItemParams) (r ReadMenuItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateGuest implements updateGuest operation.
//
// Updates a Guest and persists changes to storage.
//
// PATCH /guests/{id}
func (UnimplementedHandler) UpdateGuest(ctx context.Context, req UpdateGuestReq, params UpdateGuestParams) (r UpdateGuestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMenuItem implements updateMenuItem operation.
//
// Updates a MenuItem and persists changes to storage.
//
// PATCH /menu-items/{id}
func (UnimplementedHandler) UpdateMenuItem(ctx context.Context, req UpdateMenuItemReq, params UpdateMenuItemParams) (r UpdateMenuItemRes, _ error) {
	return r, ht.ErrNotImplemented
}
